version: '3.7'

services:
  db:
    container_name: mysql-3
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot    
    ports:
      - "3307:3306"
    volumes:
      - db-vol:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin-3
    image: phpmyadmin
    ports:
      - 8081:80

volumes:
  db-vol: